services:
  ollama:
    build:
      context: ./docker
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: ["serve"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - OLLAMA_NUM_THREADS=1  # Minimize CPU fallback
      - CUDA_VISIBLE_DEVICES=0  # Lock to GPU 0

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    environment:
      OLLAMA_HOST: "http://ollama:11434"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1g"

volumes:
  ollama_data: